# Generated by Django 3.2.25 on 2024-06-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_auto_20240606_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
    ]
